:PROPERTIES:
:ID:       5016f76a-f2ba-489c-96ec-316ab4a91bd9
:END:
#+title: Group

In [[id:121106e1-bfee-4e5b-80b9-51446259a4cd][Group Theory]], a group is a collection of elements *grouped* by a /common binary operation/. The elements can be of any type: real numbers, complex numbers, matrices etc. The common operation can also be anything: addition, multiplication etc.

* Axioms a group must satisfy 
:PROPERTIES:
:ID:       223969e9-d808-45fc-bf36-335c4468c0b3
:END:
** Closure
:PROPERTIES:
:ID:       e0f866a1-2c2e-4483-80bc-d163ec724dcb
:END:
The operation of the group takes any two elements from the group, and returns an element which is also a part of the group.
\[
a \cdot b = c
\]

** Associativity
:PROPERTIES:
:ID:       bb14b316-ab6d-4742-a6d2-ee05167f4f6f
:END:
\[
(a \cdot b) \cdot c = a \cdot (b \cdot c)
\]

** Neutral
:PROPERTIES:
:ID:       0d63195a-0035-4e4c-97a1-47c4c77b2403
:END:
Every group contains a so called *neutral* element $e$, which when operated upon with any other element, gives the element itself. 
\[
e\cdot a = a = a \cdot e
\]

** Inverse
:PROPERTIES:
:ID:       bd4b7100-2033-4444-81bf-b29ca04aeb30
:END:
Every element has an *inverse* element, which when operated with the original element, returns the neutral element.
\[
a \cdot a^{-1} = e
\]

* Order of a group
:PROPERTIES:
:ID:       bf1f493c-8bb3-4158-a9c9-f9bd67cb2684
:END:
The number of elements in a group is called the order of a group. E.g.
\[
\|Z\| = \infty
\]
* Semi groups
:PROPERTIES:
:ID:       49643318-8d77-471e-9790-d82ad2602774
:END:
A semi group is a structure which satisfies the [[id:e0f866a1-2c2e-4483-80bc-d163ec724dcb][closure property]] as well as the [[id:bb14b316-ab6d-4742-a6d2-ee05167f4f6f][associativity property]].
* Cyclic groups
:PROPERTIES:
:ID:       61fd5565-98fc-4318-9246-325300b6acfa
:END:
It's a category of finite-element groups of order =n= grouped by the /add/ operation. These type of groups contain the whole numbers starting from =0= and going upto =n-1=. E.g.

\[
Z_6 = \{0, 1, 2, 3, 4, 5\}
\]

When we add two elements of the group and the result comes out to be greater than =n=, then we just wrap it around by taking the remainder when divided by =n=:

\begin{align*}
3 + 3 &= 0 \\
3 + 5 &= 2
\end{align*}

* Dihedral groups
:PROPERTIES:
:ID:       0d7067de-14b8-4b0d-8e59-07d356c3f2a1
:END:
It is a *non-commutative* group, i.e.
\[
a \circ b \neq b\circ a
\]

It is denoted by $D_n$.

** How does it work
Chose a polygon with number of edges equal to =n=. WLOG, let us consider a hexagon (6 sides), hence the group becomes $D_6$. Here, the elements of the group represent /all the different rotations/flips possible for the hexagon such that the final orientation remains the same/.
In case of a hexagon, the shape can be rotated 6 times to get the same orientation; and an additional 6 times *after* it is flipped. Hence, a total of 12 different elements.
** Operation of a dihedral group
The operation used in a dihedral group is the /chaining operation/, in which we chain two different rotations/flips to get another rotation/flip.
E.g. consider two elements:
- hexagon rotated clockwise at 60\deg
- hexagon rotated clockwise at 120\deg

And then we operate on these two elements, then it would be effectively rotating the hexagon clockwise at 180\deg.
