#+TITLE: Docker

* Cheatsheet
- To pull the image for centos from [[https://hub.docker.com/][docker hub]]:
#+begin_src shell
docker pull centos
#+end_src

- on the docker hub page for a specific image, there will be different version tags available for the image. To use a specific tag for the image:
#+begin_src shell
docker pull centos:latest
#+end_src

- To create a new docker container with the name foo:
#+begin_src shell
docker run -d -t --name foo centos
#+end_src

- To list all the docker containers:
#+begin_src shell
docker ps -a
#+end_src

- To get a bash shell inside the container named foo:
#+begin_src shell
docker exec -it foo bash
#+end_src

- To stop a running container:
#+begin_src shell
docker stop <container>
#+end_src

* Dockerfile
** Basic Syntax
Create a file named =Dockerfile=
*** Base image
#+begin_src dockerfile
FROM ubuntu
#+end_src

*** Specifying maintainer (optional)
Specifying a maintainer is optional, but it is recommended.
#+begin_src dockerfile
MAINTAINER Sabyasachi Bhoi <sabyabhoi@gmail.com>
#+end_src
The name can also be omitted.

*** Execute commands
**** RUN
A =RUN= command is executed when the container is first created.
#+begin_src dockerfile
RUN apt-get update
#+end_src

**** CMD
A =CMD= command is executed every time the container is launched.
#+begin_src dockerfile
CMD ["echo", "Hello world"]
#+end_src

** Building the file
#+begin_src bash
docker build /path/to/dockerfile/dir/
#+end_src

*** Mention name and version of image
#+begin_src bash
docker build -t customUbuntu:1.0.0 /path/to/dockerfile/dir/
#+end_src
