#+TITLE: Nmap

* Ping entire network
#+begin_src bash
nmap -sP 172.16.140.0/23
#+end_src
The =-s= flag stands for /scan/. It is followed by =P=, which means it is a /ping scan/.
* Check for open ports
** TCP Requests
#+begin_src bash
sudo nmap -sT -p 80,443 172.16.140.0/23
#+end_src
- =-sT= means it's a /TCP Scan/, using a three-way handshake: *SYN, SYN-ACK, ACK*.
- If you don't pass in the =-p= flag, it scans the top 1000 most common ports.
- When the port is identified as open, nmap sends a *RST* flag (meaning /reset/) to end the connection.
- This scan can be recognized by an /intrustion detection system./
** Stealth scan
#+begin_src bash
sudo nmap -sS -p 80,443 172.16.140.0/23
#+end_src
- It doesn't perform the full three-way handshake.
- It doesn't return an *ACK* reponse when it receives a *SYN-ACK* response.

* See what OS the host is using
#+begin_src bash
sudo nmap -O $IP
#+end_src

* Combo scan
#+begin_src bash
sudo nmap -A $IP
#+end_src
=-A= performs OS and version detection, script scanning and traceroute.
* Obfuscation
#+begin_src bash
sudo nmap -sS -D $DECOY_IP $IP
#+end_src
We use the =-D= flag to send requests to the target IP from our IP as well as the decoy IP.
