:PROPERTIES:
:ID:       e5e9c082-59a8-44c0-bf38-75351f4a580c
:ROAM_REFS: https://www.youtube.com/watch?v=wsT2bBo4XT8
:END:
#+title: How to spend money to buy happiness

* Spend money on experiences rather than on things
** Anticipation
- Anticipation is basically free happiness.
- When we we're buying stuff, a major part of our pleasure is anticipating the thing we're going to buy.
- So it's more easier to anticipate experiences rather than material objects.
** Avoiding comparison trap
E.g. it's easier to compare the car you have with a Tesla Model X, but relatively difficult to compare your trip to Goa to your friends trip to Ladakh.
** Sharing with other people
- Sharing experiences with other people is only going to amplify the impact of the experience itself.
* Spend money on friends
:PROPERTIES:
:ROAM_REFS: https://www.youtube.com/watch?v=ZwGEQcFo9RE
:END:
- Spending money on friends has been seen to improve happiness levels for both the friends and the person spending the money.
* Spend money on health
- Any hit to our health (either physical or mental) has a heavy impact on our happiness.
* Spend money on smaller things rather than big ones
Due to diminishing marginal utility, the amount of happiness we'd get from buying a big thing would be lesser than buying smaller things that compensate for the big thing.
* Delay consumption whenever possible
- Whenever we delay our consumption, we're declining /instant gratification/.
- Delaying consumption also increases anticipation for future consumption.
* Spend money to buy back your time
- People feel happier when they do the things that set decide for themselves, rather than when they're obligated to do it.
- Building passive sources of income etc. essentially free us off from obligations we don't necessarily enjoy.
* Spend money to remove salient negatives
Outsource the things that you don't necessarily enjoy in your life, like cleaning the bathroom.
* Spend money on things than enable other interesting activities
- If we're unable to spend money on experiences, we should buy things that enable such activities.
- E.g. if I buy a car, then I shouldn't necessarily view it as a car, but as an opportunity to, let's say going out on road trips.

* Spend money on charity
