:PROPERTIES:
:ID:       34908ece-3d73-4a01-9aa1-cdc313f469df
:END:
#+title: Interrupts
#+filetags: :CS:

* Types of interrupts
In the [[id:2c8335ac-5776-4dba-9cbd-0873a7555f13][8086 Microprocessor]], interrupts are of two types:
** Hardware Interrupts
*** Maskable
- This is invoked via the $\textrm{INTR}$ and $\overline{\textrm{INTA}}$ pins.
- The user can ignore these kinds of interrupts

*** Non-Maskable
- This is invoked via the $\textrm{NMI}$ pin.
- Such interrupts signify critical system issues and cannot be ignored by the microprocessor.

** Software Interrupts
These can be called using the ~INT~ instruction:
#+begin_src asm
	INT 03H ;; calls the 3rd interrupt
#+end_src

* Interrupt Vector Table
:PROPERTIES:
:ID:       a836321a-1cd8-48eb-8dfe-27ad7e4a2d53
:ROAM_ALIASES: IVT
:END:

- It is a data structure that associates a list of interrupt handlers with a list of interrupt requests in a table of interrupt vectors.
- For the n^th interrupt, the ~IP~ is stored in ~4n~ and ~4n + 1~ addresses, and ~CS~ is stored in ~4n + 2~ and ~4n + 3~ addresses.

* Creating custom interrupts
The following code creates an /Interrupt Service Routine (ISR)/ which is going to be stored in the 9^th index in the interrupt vector table.
#+begin_src asm
	ISR09H PROC
		MOV AX, BX
		ADD AX, 3
		INC BX
	ENDP
#+end_src

* Intel Dedicated Interrupts
** Type 0: Divide by Zero
- Called automatically when there is a divide by zero error
** Type 1: Single Step Interrupt
- If the Trap Flag is set, then this interrupt is called on every instruction.
** Type 2: NMI
- Non-maskable interrupts
** Type 3: Break point interrupt 
** Type 4: Overflow
- Generated by ~INTO~
** Type 5: Bound
- Called by the ~BOUND~ instruction

#+begin_src asm
	BOUND AX, [DATA]
#+end_src

- Here, ~AX~ is compared to ~[DATA]~, then ~[DATA + 2]~
- If ~AX~ is not in the range of content of ~[DATA]~ or ~[DATA + 2]~ (both inclusive), then this particular interrupt is triggered.

* Interrupt Priority
1. Internal Interrupts & Software Interrupts /(highest priority)/
2. NMI
3. INTR /(lowest priority)/
