:PROPERTIES:
:ID:       2d01cd01-961a-4e2a-87ea-a6df0f5752e9
:END:
#+title:Success Mechanism present inside us
#+filetags: :BOOK:

- Like a guided missile, we're equiped with a success mechanism which is locked into a particular goal.
- The goal is set in the form of mental images.
  - The key image which our success mechanism targets is our [[id:ad031360-1f8a-46fc-a1b5-a13e914043ef][Self-Image]].
- If my self-image is that of a confident or smart person, then my success mechanism is going to drive me to become a confident or smart person respectively.
- Even small victories can be used as reference points for setting success-oriented self-image.

* Principles under which our success mechanism operates
1. Works to reach a goal:
   - If the goal is known, then it steers towards it.
   - If it's unknown, then it works to discover it.
2. The mechanism automatically comes up with a path towards the goal (no matter how weird or abrupt it may be); we just need to set the goal image to achieve it.
3. Don't be afraid of temporary failures, since they provide the negative feedback necessary for correction.
4. After trial and error, original errors are forgotten and the successful response is remembered forever. (Like tying your shoelaces).
5. Trust the mechanism; don't force it by becoming anxious
   - Don't wait for a proof, it will come when it's needed.
