:PROPERTIES:
:ID:       986712c7-f5cd-4baf-8cce-92c23b713c3b
:END:
#+title: Habits

* How to Create Good Habits
:PROPERTIES:
:ID:       af51e750-727e-4318-bd3d-cd70f06ab2d7
:END:
** Make it Obvious
1. Fill out the Habits Scorecard. Write down your current habits to become aware of them.
2. Use implementation intentions: "I will *[BEHAVIOR]* at *[TIME]* in *[LOCATION]*."
3. Use habit stacking: "After *[CURRENT HABIT]*, I will *[NEW HABIT]*."
4. Design your environment. Make the cues of good habits obvious and visible. 
** Make it Attractive
1. Use temptation bundling. Pair an action you want to do with an action you need to do.
2. Join a culture where your desired behavior is the normal behavior.
3. Create a motivation ritual. Do something you enjoy immediately before a difficult habit. 
** Make it Easy
1. Reduce friction. Decrease the number of steps between you and your good habits.
2. Prime the environment. Prepare your environment to make future actions easier.
3. Master the decisive moment. Optimize the small choices that deliver outsized impact.
4. Use the Two-Minute Rule. Downscale your habits until they can be done in two minutes or less.
5. Automate your habits. Invest in technology and onetime purchases that lock in future behavior. 
** Make it Satisfying
1. Use reinforcement. Give yourself an immediate reward when you complete your habit.
2. Make “doing nothing” enjoyable. When avoiding a bad habit, design a way to see the benefits.
3. Use a habit tracker. Keep track of your habit streak and “don’t break the chain.”
4. Never miss twice. When you forget to do a habit, make sure you get back on track immediately. 
* How to Break Bad Habits
:PROPERTIES:
:ID:       7e818260-9c60-430f-96ec-43944ed2f1f0
:END:
** Make it Invisible
1. Reduce exposure. Remove the cues of your bad habits from your environment. 
** Make it Unattractive
1. Reframe your mindset. Highlight the benefits of avoiding your bad habits. 
** Make it Difficult
1. Increase friction. Increase the number of steps between you and your bad habits.
2. Use a commitment device. Restrict your future choices to the ones that benefit you. 
** Make it Unsatisfying
1. Get an accountability partner. Ask someone to watch your behavior.
2. Create a habit contract. Make the costs of your bad habits public and painful. 
